const bcrypt = require('bcryptjs');
const User = require('../models/User');
const ServiceProvider = require('../models/ServiceProvider');
const Admin = require('../models/Admin');
const OtpToken = require('../models/OtpToken');
const asyncHandler = require('../utils/asyncHandler');
const generateToken = require('../utils/generateToken');

const OTP_TTL_MS = 5 * 60 * 1000;
const MAX_OTP_ATTEMPTS = 5;

// POST /api/auth/check-mobile
// Called BEFORE the client sends the OTP. Only looks up whether the number is registered —
// never creates anything here. The client uses the returned newUser flag to decide navigation
// after OTP verify.
const checkMobile = asyncHandler(async (req, res) => {
  const { phone, role } = req.body;

  if (!phone || !['user', 'provider'].includes(role)) {
    return res.status(400).json({ message: 'phone and role (user|provider) are required' });
  }

  const Model = role === 'user' ? User : ServiceProvider;
  const existing = await Model.findOne({ phone });

  res.json({ newUser: !existing });
});

// POST /api/auth/send-otp
// Generates and stores a one-time code for this phone+role. There is no SMS gateway configured,
// so — mirroring how this backend already degrades gracefully when Razorpay/other integrations
// aren't configured — the code is returned in the response (and logged) outside production so
// the flow is testable end-to-end without a paid SMS provider.
const sendOtp = asyncHandler(async (req, res) => {
  const { phone, role } = req.body;

  if (!phone || !['user', 'provider'].includes(role)) {
    return res.status(400).json({ message: 'phone and role (user|provider) are required' });
  }

  const code = String(Math.floor(100000 + Math.random() * 900000));
  const codeHash = await bcrypt.hash(code, 10);

  await OtpToken.findOneAndDelete({ phone, role });
  await OtpToken.create({ phone, role, codeHash, expiresAt: new Date(Date.now() + OTP_TTL_MS) });

  const response = { message: 'OTP sent' };
  if (process.env.NODE_ENV !== 'production') {
    console.log(`[dev] OTP for ${phone} (${role}): ${code}`);
    response.devOtp = code;
  }

  res.json(response);
});

// POST /api/auth/verify-otp
// Verifies the code generated by send-otp, then finds-or-creates the account for the requested role.
const verifyOtp = asyncHandler(async (req, res) => {
  const { phone, role, otp, name } = req.body;

  if (!phone || !['user', 'provider'].includes(role) || !otp) {
    return res.status(400).json({ message: 'phone, role (user|provider) and otp are required' });
  }

  const token = await OtpToken.findOne({ phone, role });
  if (!token) {
    return res.status(400).json({ message: 'OTP expired or not requested. Please request a new one.' });
  }

  if (token.attempts >= MAX_OTP_ATTEMPTS) {
    await token.deleteOne();
    return res.status(400).json({ message: 'Too many incorrect attempts. Please request a new OTP.' });
  }

  const match = await bcrypt.compare(String(otp), token.codeHash);
  if (!match) {
    token.attempts += 1;
    await token.save();
    return res.status(400).json({ message: 'Invalid OTP' });
  }

  await token.deleteOne();

  const Model = role === 'user' ? User : ServiceProvider;
  let account = await Model.findOne({ phone });

  let isNewAccount = false;
  if (!account) {
    isNewAccount = true;
    account = await Model.create({
      name: name || 'New ' + (role === 'user' ? 'User' : 'Service Provider'),
      phone,
    });
  }

  const jwtToken = generateToken({ id: account._id, role });

  res.status(isNewAccount ? 201 : 200).json({
    token: jwtToken,
    isNewAccount,
    account,
  });
});

// POST /api/auth/admin/login
const adminLogin = asyncHandler(async (req, res) => {
  const { email, password } = req.body;

  if (!email || !password) {
    return res.status(400).json({ message: 'Email and password are required' });
  }

  const account = await Admin.findOne({ email: email.toLowerCase() });
  if (!account) {
    return res.status(401).json({ message: 'Invalid credentials' });
  }

  const match = await bcrypt.compare(password, account.password);
  if (!match) {
    return res.status(401).json({ message: 'Invalid credentials' });
  }

  const token = generateToken({ id: account._id, role: 'admin' });

  res.json({ token, account: { id: account._id, name: account.name, email: account.email } });
});

module.exports = { checkMobile, sendOtp, verifyOtp, adminLogin };
